#!/bin/bash

#ensure 'getopts' works with 'source' command
OPTIND=1

G_VERSION="stable"
G_REVISION=""
Gb_revisionSet=0
G_SYNOPSIS="

    NAME
    
        chb-fs
        
    SYNOPSIS
    
        chb-fs [<version>] [<revision>]
        
    ARGS
    
        <version> (Default \"$G_VERSION\")
        Source the FreeSurfer environment for the given version.

	<revision> (No default)
	Specify a revision of the version. This is only necessary when multiple
	revisions exist, for example in the case of the 'stable' version there
	might be revision '5.0.0' and '5.1.0' installed on the system. If not
	specified, the environment will default to whatever has been configured
	as the default revsion for a given version. This default will have been
	setup by the system administrator.
        
    DESCRIPTION
    
        'chb-fs' is a simple script to easily source different environments 
        for FreeSurfer.
        
        If called without any arguments, it will default to the stable
        version of FreeSurfer, currently \"$G_VERSION$G_REVISION\".
        
        
    HISTORY
    
        May 30 2012
        o Initial development.
"
function synopsis_show
{
        # ARGS
        # $1            in (opt)                if passed, exit to shell
        #                                       passing code $1.
        echo "USAGE:"
        echo "$G_SYNOPSIS"
        if (( $# == 1 )) ; then exit $1 ; fi
}

# This handles the following:
#       -x                      : show help and exit
#       1st command ling arg    : set G_VERSION
#       if exist 2nd arg        : set G_REVISION
#       additional args         : show help and exit
if (( $# <= 2 )) ; then
    if [[ $1 == "-x" ]] ; then synopsis_show 1; fi
    if (( ${#1} )) ; then G_VERSION=$1;  fi
    if (( $#==2 )) ; then G_REVISION=$2; fi
else
    synopsis_show 1
fi

echo "version:  $G_VERSION"
if (( ${#G_REVISION} )) ; then
    echo "revision: $G_REVISION"
    G_REVISION="-$G_REVISION"   # This is because installs on the filesystem
                                # are <version>-<revision>.
else
    echo "revision: -system default-"
fi

OS=$(uname -a | awk '{print $1}')
echo "Host type is $HOSTTYPE-${OS}"

export PACKAGEDIR=/chb/freesurfer/${HOSTTYPE}-${OS}/packages
export FSL_DIR=${PACKAGEDIR}/fsl419
export SUBJECTS_DIR=$(pwd)

source ${PACKAGEDIR}/freesurfer/${G_VERSION}${G_REVISION}/SetUpFreeSurfer.sh
source ${FSL_DIR}/etc/fslconf/fsl.sh
unset TCLLIBPATH
unset TCL_LIBRARY
unset TK_LIBRARY
unset TIX_LIBRARY

OS=$(uname -a | awk '{print $1}')
export PROMPTPREFIX="[$name:${HOSTTYPE}-${OS}-chb-fs-${G_VERSION}${G_REVISION}]"

# why Slicer?
export PATH=$PATH:/chb/freesurfer/${HOSTTYPE}-${OS}/packages/mricron:/chb/freesurfer/${HOSTTYPE}-${OS}/packages/dtk
#:/chb/freesurfer/${HOSTTYPE}-${OS}/packages/Slicer/current/

# why cmp?
#export PYTHONPATH=$PYTHONPATH:/chb/arch/python/cmp
