declare -a a_PICES=(
        rc-drno
        rc-twice
        rc-live
        rc-golden
        )

declare -a a_FNNDSC=(
        titan
        pangea
        hollywood
        centauri
        ulsan
        havana
	patmos
        goldreef
        skopje
        seville
        arcadia
        london
        simonstown
        pretoria
        capetown
        shaka
        sunnyside
        rio
        oklahoma
        naples
        toledo
        winterfell
        westeros
        maracuja
        longwood
        hercules
        hippocrates
        red
        sox
        santorini
        cube-next
        athena
        sun
        chris-tmp
        chopin
        dover 
        oxford
        radview
        centurion
        dubrovnik
        megalodon
        luna
        fiona-bch
        antalya
        montreal
	chris-next
        zebra
        rhino
	meerkat
        hagrid
        johannesburg
	fnndsc
	fnndsc-clone
	fnndsc.childrens.harvard.edu
	severus
	bellatrix
	nightwing
	clayface
        poisonivy
        riddler
        dobby
        sirius
        harleyq
)

