declare -a a_PICES=(
        rc-drno
        rc-twice
        rc-live
        rc-golden
        )

declare -a a_FNNDSCold=(
        titan
        pangea
        hollywood
        centauri    
        ulsan
        havana
        patmos
        goldreef
        skopje
        seville
        arcadia
        london
        simonstown
        pretoria
        capetown
        shaka
        sunnyside
        rio
        oklahoma
        naples
        toledo
        winterfell
        westeros
        maracuja
        longwood
        hercules
        hippocrates
        red
        sox
        santorini
        cube-next
        athena
        sun
        chris-tmp
        chopin
        dover 
        oxford
        radview
        centurion
        dubrovnik
        megalodon
        luna
        fiona-bch
        antalya
        montreal
        chris-next
        zebra
        rhino
        meerkat
        hagrid
        johannesburg
        fnndsc
        fnndsc-clone
        fnndsc.childrens.harvard.edu
        severus
        bellatrix
        nightwing
        clayface
        poisonivy
        riddler
        dobby
        sirius
        harleyq
)

declare -a a_FNNDSC=(
        titan
        pangea
        hollywood
        rodinia 
        ulsan
        havana
        patmos
        goldreef
        skopje
        seville
        arcadia
        london
        simonstown
        cube-next 
        capetown
        shaka
        sunnyside
        rio
        oklahoma
        naples
        toledo
        maracuja
        longwood
        hercules
        hippocrates
        red
        sox
        santorini
        athena
        sun
        chris-tmp
        chopin
        stormwind 
        oxford
        radview
        centurion
        dubrovnik
        megalodon
        luna
        chris-next
        zebra
        rhino
        meerkat
        hagrid
        johannesburg
        fnndsc
        severus
        sirius
)

