#!/bin/bash

#ensure 'getopts' works with 'source' command
OPTIND=1

G_VERSION="stable"
G_REVISION=""
Gb_revisionSet=0
G_SYNOPSIS="

    NAME
   
        neuro-fs
        
    SYNOPSIS
    
        neuro-fs [<version>] [<revision>]
        
    ARGS
    
        <version> (Default \"$G_VERSION\")
        Source the FreeSurfer environment for the given version.

	<revision> (No default)
	Specify an optional revision of the version. This is only necessary when 
	multiple revisions of a given version exist, for example in the case of 
	the 'stable' version there might be revision '5.0.0', '5.1.0', and '5.2' 
	installed concurrently on the system. If the <revision> is not 
	specified, the environment will default to whatever has been configured
	as the default revsion for a given version. This default will have been
	setup by the system administrator.
        
    DESCRIPTION
    
        'neuro-fs' is a simple script to easily source different environments 
        for FreeSurfer.
        
        If called without any arguments, it will setup the current default
        version of FreeSurfer for this system, which has been 
        configured here as \"$G_VERSION$G_REVISION\".
        
    NB!
        
        To have variables set by this script to be valid in the caller (i.e.
        parent's scope), this script *must* be sourced and not executed. That 
        means instead of typing:
        
                $>neuro-fs stable
                
        to setup the FreeSurfer stable enviroment, you have to type:
        
                $>. neuro-fs stable
                
        note the dot '.' at the beginning! Without this dot, the specified
        FreeSurfer environment will NOT be initialized.
        
    HISTORY
    
        May 30 2012
        o Initial development.
        
        Mar 05 2013
        o Add logic for PICES local use.
        
	Jan 24 2014
	o Switch 'chb' for 'neuro'.
"
function synopsis_show
{
        # ARGS
        # $1            in (opt)                if passed, exit to shell
        #                                       passing code $1.
        echo "USAGE:"
        echo "$G_SYNOPSIS"
        if (( $# == 1 )) ; then exit $1 ; fi
}

# This handles the following:
#       -x                      : show help and exit
#       1st command ling arg    : set G_VERSION
#       if exist 2nd arg        : set G_REVISION
#       additional args         : show help and exit
if (( $# <= 2 )) ; then
    if [[ $1 == "-x" ]] ; then synopsis_show 1; fi
    if (( ${#1} )) ; then G_VERSION=$1;  fi
    if (( $#==2 )) ; then G_REVISION=$2; fi
else
    synopsis_show 1
fi

echo "version:  $G_VERSION"

if [[ $G_VERSION == "dev" ]] ; then
    echo "+----------+"
    echo "| WARNING! |____________________________________________" 
    echo "+------------------------------------------------------+"
    echo "| You have chosen the FreeSurfer developer version.    |"
    echo "| Be aware that this version of FreeSurfer might be    |"
    echo "| possibly unstable, with new and untested features.   |"
    echo "| The 'dev' version also changes without announcement. |"
    echo "|                                                      |"
    echo "| Do NOT use this version for production or analysis   |"
    echo "| work.                                                |"
    echo "|                                                      |"
    echo "| Unless you are a developer writing FreeSurfer code   |"
    echo "| you probably don't want to use this. Use the         |" 
    echo "| 'stable' version instead.                            |"
    echo "+------------------------------------------------------+"
    echo ""
fi

if (( ${#G_REVISION} )) ; then
    echo "revision: $G_REVISION"
    G_REVISION="-$G_REVISION"   # This is because installs on the filesystem
                                # are <version>-<revision>.
else
    echo "revision: -system default-"
fi

OS=$(uname -a | awk '{print $1}')
HOSTTYPE=$(echo $HOSTTYPE | awk '{print tolower($0)}')
echo "Host type is ${HOSTTYPE}-${OS}"

export PACKAGEDIR=/neuro/arch/${HOSTTYPE}-${OS}/packages

export DTDIR=${PACKAGEDIR}/dtk/current/dtk
export DSI_PATH=${DTDIR}/matrices

export PATH=$PATH:${CHB_SCRIPTPATH}:${FSLDIR}:${FSLDIR}/bin
export FSL_DIR=${PACKAGEDIR}/fsl/current
export SUBJECTS_DIR=$(pwd)

source ${PACKAGEDIR}/freesurfer/${G_VERSION}${G_REVISION}/SetUpFreeSurfer.sh
source ${FSL_DIR}/etc/fslconf/fsl.sh
unset TCLLIBPATH
unset TCL_LIBRARY
unset TK_LIBRARY
unset TIX_LIBRARY

OS=$(uname -a | awk '{print $1}')
export PROMPTPREFIX="[$name:${HOSTTYPE}-${OS}-neuro-fs-${G_VERSION}${G_REVISION}]"

export PATH=$PATH:${PACKAGEDIR}/mricron:${PACKAGEDIR}/dtk/current/dtk

# MatLAB exports
## Matlab compiler Runtime (MCR)
export MCRROOT=/neuro/arch/x86_64-Linux/packages/matlab/MATLAB_Compiler_Runtime/current
export LD_LIBRARY_PATH=/neuro/arch/x86_64-Linux/packages/matlab/MATLAB_Compiler_Runtime/current/runtime/glnxa64:/neuro/arch/x86_64-Linux/packages/matlab/MATLAB_Compiler_Runtime/current/bin/glnxa64:/neuro/arch/x86_64-Linux/packages/matlab/MATLAB_Compiler_Runtime/current/sys/os/glnxa64:/neuro/arch/x86_64-Linux/packages/matlab/MATLAB_Compiler_Runtime/current/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/neuro/arch/x86_64-Linux/packages/matlab/MATLAB_Compiler_Runtime/current/sys/java/jre/glnxa64/jre/lib/amd64/server:/neuro/arch/x86_64-Linux/packages/matlab/MATLAB_Compiler_Runtime/current/sys/java/jre/glnxa64/jre/lib/amd64:$LD_LIBRARY_PATH
export XAPPLRESDIR=/neuro/arch/x86_64-Linux/packages/matlab/MATLAB_Compiler_Runtime/current/X11/app-defaults

