#!/bin/bash

#ensure 'getopts' works with 'source' command
OPTIND=1

G_VERSION="stable"
G_REVISION=""
Gb_revisionSet=0
G_SYNOPSIS="

    NAME
    
        nmr-fs
        
    SYNOPSIS
    
        nmr-fs [<version>] [<revision>]
        
    ARGS
    
        <version> (Default \"$G_VERSION\")
        Source the FreeSurfer environment for the given version.

	<revision> (No default)
	Specify an optional revision of the version. This is only necessary when 
	multiple revisions of a given version exist, for example in the case of 
	the 'stable' version there might be revision '5.0.0', '5.1.0', and '5.2' 
	installed concurrently on the system. If the <revision> is not 
	specified, the environment will default to whatever has been configured
	as the default revsion for a given version. This default will have been
	setup by the system administrator.
        
    DESCRIPTION
    
        'nmr-fs' is a simple script to easily source different environments 
        for FreeSurfer, localized for the MGH Martinos NMR center as well as
	the Partners HPC cluster.
        
        If called without any arguments, it will setup the current default
        version of FreeSurfer for this system, which has been 
        configured here as \"$G_VERSION$G_REVISION\".
        
    NB!
        
        To have variables set by this script to be valid in the caller (i.e.
        parent's scope), this script *must* be sourced and not executed. That 
        means instead of typing:
        
                $>nmr-fs stable
                
        to setup the FreeSurfer stable enviroment, you have to type:
        
                $>. nmr-fs stable
                
        note the dot '.' at the beginning! Without this dot, the specified
        FreeSurfer environment will NOT be initialized.
        
    HISTORY
    
        Apr 01 2013
        o Adapted from 'chb-fs'. 
        
"
function synopsis_show
{
        # ARGS
        # $1            in (opt)                if passed, exit to shell
        #                                       passing code $1.
        echo "USAGE:"
        echo "$G_SYNOPSIS"
        if (( $# == 1 )) ; then exit $1 ; fi
}

# This handles the following:
#       -x                      : show help and exit
#       1st command ling arg    : set G_VERSION
#       if exist 2nd arg        : set G_REVISION
#       additional args         : show help and exit
if (( $# <= 2 )) ; then
    if [[ $1 == "-x" ]] ; then synopsis_show 1; fi
    if (( ${#1} )) ; then G_VERSION=$1;  fi
    if (( $#==2 )) ; then G_REVISION=$2; fi
else
    synopsis_show 1
fi

echo "version:  $G_VERSION"

if [[ $G_VERSION == "dev" ]] ; then
    echo "+----------+"
    echo "| WARNING! |____________________________________________" 
    echo "+------------------------------------------------------+"
    echo "| You have chosen the FreeSurfer developer version.    |"
    echo "| Be aware that this version of FreeSurfer might be    |"
    echo "| possibly unstable, with new and untested features.   |"
    echo "| The 'dev' version also changes without announcement. |"
    echo "|                                                      |"
    echo "| Do NOT use this version for production or analysis   |"
    echo "| work.                                                |"
    echo "|                                                      |"
    echo "| Unless you are a developer writing FreeSurfer code   |"
    echo "| you probably don't want to use this. Use the         |" 
    echo "| 'stable' version instead.                            |"
    echo "+------------------------------------------------------+"
    echo ""
fi

if (( ${#G_REVISION} )) ; then
    echo "revision: $G_REVISION"
    G_REVISION="-$G_REVISION"   # This is because installs on the filesystem
                                # are <version>-<revision>.
else
    echo "revision: -system default-"
fi

OS=$(uname -a | awk '{print $1}')
echo "Host type is $HOSTTYPE-${OS}"

export PACKAGEDIR=/usr/pubsw/packages
export FSL_DIR=${PACKAGEDIR}/fsl/current
export SUBJECTS_DIR=$(pwd)
export FREESURFER=/usr/local/freesurfer
ENV=nmr

if (( $(hostname | grep eris | wc -l) )) ; then
	module load gcc-4.4
	module load java-1.6_18
	module load python-2.6
	module load fftw-3.2.2
	module load freesurfer-5.1.0
	export FREESURFER=~/arch/x86_64-Linux/packages/freesurfer
	echo $FREESURFER
	ENV=erisone
	FSL_DIR=/source/fsl-4.1.9/Install/fsl
fi
echo $FREESURFER
source ${FREESURFER}/${G_VERSION}${G_REVISION}/SetUpFreeSurfer.sh
source ${FSL_DIR}/etc/fslconf/fsl.sh
unset TCLLIBPATH
unset TCL_LIBRARY
unset TK_LIBRARY
unset TIX_LIBRARY

OS=$(uname -a | awk '{print $1}')
export PROMPTPREFIX="[$name:${HOSTTYPE}-${OS}-${ENV}-fs-${G_VERSION}${G_REVISION}]"

export PATH=$PATH:${PACKAGEDIR}/mricro:${PACKAGEDIR}/dtk


